version: 2

defaults: &defaults
  working_directory: ~/source
  docker:
      - image: vnkhangnt/buildpack-deps:trusty
        environment:
          FFMPEG_VERSION: 3.3.2
  steps:
      - checkout
      - run:
          name: Compile FFmpeg
          command: |
            mkdir -p build_logs;
            export FINAL_DIR=$(pwd)/artifacts/$TARGET;
            export BUILD_DIR=$(pwd)/build_scripts/build_dir && mkdir -p $BUILD_DIR;
            ./build_scripts/build_ffmpeg.sh $TARGET $BUILD_DIR $FINAL_DIR;
      - run: 
          name: Copy error report
          command: |
            mkdir -p build_logs/ffmpeg; 
            cp build_scripts/ffmpeg-$FFMPEG_VERSION/config.log build_logs/ffmpeg/ || true;
          when: on_fail
      - store_artifacts:
          path: build_logs
      - persist_to_workspace:
          root: artifacts
          paths:
            - $TARGET/*

jobs:
  build_arm:
    environment:
      TARGET: arm
    << : *defaults

  build_arm_v7a:
    environment:
      TARGET: armv7-a
    << : *defaults

  build_arm_v7a_neon:
    environment:
      TARGET: arm-v7n
    << : *defaults

  build_arm_v8a:
    environment:
      TARGET: arm64-v8a
    << : *defaults

  build_arm_x86:
    environment:
      TARGET: i686
    << : *defaults

  build_arm_x86_64:
    environment:
      TARGET: x86_64
    << : *defaults

  build_native_linux:
    environment:
      TARGET: native
    << : *defaults

  create_release:
    docker:
      - image: vnkhangnt/buildpack-deps:trusty
    working_directory: ~/source
    steps:
      - attach_workspace:
          at: artifacts
      - run: ls artifacts/

workflows:
  version: 2
  build-and-create-release:
    jobs:
      - build_arm
      - build_arm_v7a
      - build_arm_v7a_neon
      - build_arm_v8a
      - build_arm_x86
      - build_arm_x86_64
      - build_native_linux
      - create_release:
          requires:
            - build_arm
            - build_arm_v7a
            - build_arm_v7a_neon
            - build_arm_v8a
            - build_arm_x86
            - build_arm_x86_64
            - build_native_linux

